steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hci-api:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hci-api:$COMMIT_SHA']
  # Kustomize: set the image in the kustomization.yaml file
  - name: 'gcr.io/cloud-builders/gke-deploy'
    dir: 'k8s/staging'
    entrypoint: 'kustomize'
    args:
      - 'edit'
      - 'set'
      - 'image'
      - 'gcr.io/project-id/hci-api=gcr.io/$PROJECT_ID/hci-api:$COMMIT_SHA'
  # Kustomize: apply the kustomization.yaml file
  - name: 'gcr.io/cloud-builders/gke-deploy'
    dir: 'k8s/staging'
    entrypoint: 'kustomize'
    args: ['build', '.', '-o', 'staging.yaml']
  # Deploy the application to the GKE cluster
  - name: 'gcr.io/cloud-builders/gke-deploy'
    dir: 'k8s/staging'
    args:
      - 'run'
      - '--filename=staging.yaml'
      - '--location=us-central1'
      - '--cluster=datario'
      - '--project=datario'

images:
  - 'gcr.io/$PROJECT_ID/hci-api:$COMMIT_SHA'