---
# API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hci-api-staging
  namespace: hci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hci-api-staging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: hci-api-staging
    spec:
      containers:
        - name: hci
          image: gcr.io/project-id/hci-api
          envFrom:
            - secretRef:
                name: hci-staging-secrets
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 500m
              memory: 2Gi
          command: ["/bin/bash", "/compose-entrypoint.sh"]
          livenessProbe:
            httpGet:
              path: /misc/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /misc/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always

---
# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hci-api-staging
  name: hci-api-staging
  namespace: hci
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: hci-api-staging

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hci-api-staging
  namespace: hci
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - staging.api.hci.dados.rio
      secretName: hci-api-staging-tls
  rules:
    - host: staging.api.hci.dados.rio
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hci-api-staging
                port:
                  number: 80

---
# Horizontal Pod Autoscaler (HPA) baseado em uso de CPU
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hci-api-hpa
  namespace: hci
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hci-api-staging
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
