---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unificacao-prontuarios
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: unificacao-prontuarios
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: unificacao-prontuarios
    spec:
      containers:
        - name: unificacao-prontuarios
          image: gcr.io/PROJECT_ID/IMAGE_NAME:TAG
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: unificacao-prontuarios-secrets
          readinessProbe:
            httpGet:
              path: /docs
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              memory: "1024Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      restartPolicy: Always

---
# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: unificacao-prontuarios
  name: unificacao-prontuarios
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: unificacao-prontuarios
