version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges:true
    ports:
      - "5432:5432"
  api:
    build: .
    depends_on:
      - db
    environment:
      ENVIRONMENT: dev
      INFISICAL_ADDRESS: ${INFISICAL_ADDRESS}
      INFISICAL_TOKEN: ${INFISICAL_TOKEN}
    ports:
      - "8000:80"

volumes:
  postgres-data:
