name: Lib - Tests

on:
  push:
    paths:
      - ".github/workflows/lib-*"
      - "lib/**/*"

jobs:
  tests:
    name: ${{ matrix.os }}${{ matrix.arch }} - Python ${{ matrix.python-version }} - tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x64]
        python-version: ["3.10.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}

      - name: Set up Poetry and upgrade pip
        run: |
          cd lib/
          pip install -U pip poetry

      - name: Install this package
        run: |
          cd lib/
          poetry install

      - name: Run tests
        run: |
          cd lib/
          poetry run test
